./merge_daily_AATSR_L3_mosaicking.py NorthSea 29
./merge_daily_AATSR_L3_mosaicking.py NorthSea 30
./merge_daily_AATSR_L3_mosaicking.py NorthSea 31
./merge_daily_AATSR_L3_mosaicking.py NorthSea 32
./merge_daily_AATSR_L3_mosaicking.py NorthSea 33
./merge_daily_AATSR_L3_mosaicking.py NorthSea 34
./merge_daily_AATSR_L3_mosaicking.py NorthSea 35
./merge_daily_AATSR_L3_mosaicking.py NorthSea 36
./merge_daily_AATSR_L3_mosaicking.py NorthSea 37
./merge_daily_AATSR_L3_mosaicking.py NorthSea 38
./merge_daily_AATSR_L3_mosaicking.py NorthSea 39
./merge_daily_AATSR_L3_mosaicking.py NorthSea 40
./merge_daily_AATSR_L3_mosaicking.py NorthSea 41
./merge_daily_AATSR_L3_mosaicking.py NorthSea 42
./merge_daily_AATSR_L3_mosaicking.py NorthSea 43
./merge_daily_AATSR_L3_mosaicking.py NorthSea 44
./merge_daily_AATSR_L3_mosaicking.py NorthSea 45
./merge_daily_AATSR_L3_mosaicking.py NorthSea 46
./merge_daily_AATSR_L3_mosaicking.py NorthSea 47
./merge_daily_AATSR_L3_mosaicking.py NorthSea 48
./merge_daily_AATSR_L3_mosaicking.py NorthSea 49
./merge_daily_AATSR_L3_mosaicking.py NorthSea 50
./merge_daily_AATSR_L3_mosaicking.py NorthSea 51
./merge_daily_AATSR_L3_mosaicking.py NorthSea 52
./merge_daily_AATSR_L3_mosaicking.py NorthSea 53
./merge_daily_AATSR_L3_mosaicking.py NorthSea 54
./merge_daily_AATSR_L3_mosaicking.py NorthSea 55
./merge_daily_AATSR_L3_mosaicking.py NorthSea 56
./merge_daily_AATSR_L3_mosaicking.py NorthSea 57
./merge_daily_AATSR_L3_mosaicking.py NorthSea 58
./merge_daily_AATSR_L3_mosaicking.py NorthSea 59